name: flutter_new_mytube_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  provider: ^4.3.2+1
  fl_chart: ^0.11.0
  clay_containers: ^0.2.2
  flutter_image_compress: ^0.7.0
  intl: ^0.16.1
  numberpicker: ^1.2.1
  getwidget: ^1.1.3
  firebase_messaging: ^7.0.0
  flutter_local_notifications: ^1.4.4+4
  rxdart: ^0.24.1
  flutter_sliding_tutorial: ^0.1.0
  shared_preferences: ^0.5.10
  flutter_launcher_icons: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-VariableFont_wght.ttf
          weight: 900



  uses-material-design: true
  assets:
      - images/

  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  image_path: images/video-keeper.png
  android: true
  ios: true

